name: Run node.js code
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '15,45 * * * *'
jobs:
  run-code:
    runs-on: ubuntu-latest # Use the latest Ubuntu image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Use the checkout action to clone the repository
      - name: Setup node
        uses: actions/setup-node@v2 # Use the setup-node action to install node
        with:
          node-version: '16' # Specify the node version to use
      - name: Install dependencies
        run: npm install # Install the dependencies from package.json
      - name: Run code
        run: node index.js # Run your node.js code
        env: # Set the environment variables from secrets
          PANTRYID: ${{ secrets.PANTRYID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          NAME: ${{ secrets.NAME }}
